import { expect, test } from '@playwright/test'
import { readFile, readdir } from 'node:fs/promises'

async function readProjectFile(path: string) {
  return readFile(new URL(`../${path}`, import.meta.url), 'utf8')
}

async function readSourceTree() {
  const sourceRoot = new URL('../src/', import.meta.url)
  const paths = await readdir(sourceRoot, { recursive: true })
  const sourceFiles = paths.filter(path => /\.(?:ts|tsx)$/.test(path))

  return Promise.all(sourceFiles.map(path => readFile(new URL(path.replaceAll('\\', '/'), sourceRoot), 'utf8'))).then(
    files => files.join('\n')
  )
}

test('shadcn configuration points to the source-owned UI directory', async () => {
  const config = JSON.parse(await readProjectFile('components.json')) as {
    rsc: boolean
    aliases: { ui: string; utils: string }
  }

  expect(config.rsc).toBe(true)
  expect(config.aliases.ui).toBe('@/components/ui')
  expect(config.aliases.utils).toBe('@/lib/utils')
})

test('package manifest does not depend on HeroUI', async () => {
  expect(await readProjectFile('package.json')).not.toMatch(/@heroui|@nextui/i)
})

test('theme support is wired through the root layout', async () => {
  const [manifestSource, layoutSource, themePatchSource] = await Promise.all([
    readProjectFile('package.json'),
    readProjectFile('src/app/[locale]/layout.tsx'),
    readProjectFile('patches/next-themes@0.4.6.patch')
  ])
  const manifest = JSON.parse(manifestSource) as {
    dependencies?: Record<string, string>
    pnpm?: { patchedDependencies?: Record<string, string> }
  }

  expect(manifest.dependencies?.['next-themes']).toBe('0.4.6')
  expect(manifest.pnpm?.patchedDependencies?.['next-themes@0.4.6']).toBe('patches/next-themes@0.4.6.patch')
  expect(layoutSource).toMatch(/suppressHydrationWarning/)
  expect(layoutSource).toMatch(/<ThemeProvider[^>]+defaultTheme='system'[^>]+enableSystem/)
  expect(themePatchSource.match(/if\(typeof window!=="undefined"\)return null/g)).toHaveLength(2)
})

test('TanStack Query and Redux use request-safe provider boundaries', async () => {
  const [manifestSource, layoutSource, queryProviderSource, reduxProviderSource, storeSource, hooksSource] =
    await Promise.all([
      readProjectFile('package.json'),
      readProjectFile('src/app/[locale]/layout.tsx'),
      readProjectFile('src/providers/query-provider.tsx'),
      readProjectFile('src/providers/redux-provider.tsx'),
      readProjectFile('src/store/store.ts'),
      readProjectFile('src/store/hooks.ts')
    ])
  const manifest = JSON.parse(manifestSource) as { dependencies?: Record<string, string> }

  expect(manifest.dependencies?.['@tanstack/react-query']).toBe('5.102.8')
  expect(manifest.dependencies?.['@reduxjs/toolkit']).toBe('2.12.0')
  expect(manifest.dependencies?.['react-redux']).toBe('9.3.0')
  expect(queryProviderSource).toMatch(/environmentManager\.isServer\(\)/)
  expect(queryProviderSource).toMatch(/staleTime: 60_000/)
  expect(reduxProviderSource).toMatch(/useState\(makeStore\)/)
  expect(storeSource).toMatch(/export function makeStore\(\)/)
  expect(storeSource).not.toMatch(/export const store\s*=/)
  expect(hooksSource).toMatch(/useDispatch\.withTypes<AppDispatch>\(\)/)
  expect(layoutSource).toMatch(
    /<ReduxProvider>\s*<QueryProvider>\s*<AuthProvider>\{children\}<\/AuthProvider>\s*<\/QueryProvider>\s*<\/ReduxProvider>/
  )
})

test('Iconify is the shared offline icon runtime and lucide-react is absent', async () => {
  const [
    manifestSource,
    iconSource,
    iconConfigSource,
    offlineIconSource,
    componentsSource,
    applicationSource,
    shadcnWrapper
  ] = await Promise.all([
    readProjectFile('package.json'),
    readProjectFile('src/components/ui/icon.tsx'),
    readProjectFile('src/config/icons.ts'),
    readProjectFile('src/config/icon-data.ts'),
    readProjectFile('components.json'),
    readSourceTree(),
    readProjectFile('scripts/shadcn/add-with-iconify.mts')
  ])
  const manifest = JSON.parse(manifestSource) as {
    dependencies?: Record<string, string>
    scripts?: Record<string, string>
  }
  const components = JSON.parse(componentsSource) as { iconLibrary?: string }

  expect(manifest.dependencies?.['@iconify/react']).toBe('6.0.2')
  expect(manifest.dependencies?.['lucide-react']).toBeUndefined()
  expect(components.iconLibrary).toBeUndefined()
  expect(iconSource).toMatch(/from '@iconify\/react'/)
  expect(iconConfigSource).toMatch(/lucide:/)
  expect(offlineIconSource).toMatch(/Generated by pnpm icons:generate/)
  expect(iconSource).toMatch(/offlineIcons/)
  expect(applicationSource).not.toMatch(/lucide-react/)
  expect(manifest.scripts?.['ui:add']).toMatch(/add-with-iconify/)
  expect(shadcnWrapper).toMatch(/Converted.*Iconify wrapper/)
})

test('App Router fallback boundaries are present', async () => {
  const [loadingSource, errorSource, globalErrorSource, notFoundSource, catchAllSource] = await Promise.all([
    readProjectFile('src/app/[locale]/loading.tsx'),
    readProjectFile('src/app/[locale]/error.tsx'),
    readProjectFile('src/app/global-error.tsx'),
    readProjectFile('src/app/[locale]/not-found.tsx'),
    readProjectFile('src/app/[locale]/[...rest]/page.tsx')
  ])

  expect(loadingSource).toMatch(/aria-busy='true'/)
  expect(errorSource).toMatch(/'use client'/)
  expect(errorSource).toMatch(/reset/)
  expect(globalErrorSource).toMatch(/<html lang='en'>/)
  expect(globalErrorSource).toMatch(/global-error\.module\.css/)
  expect(globalErrorSource).toMatch(/role='alert'/)
  expect(notFoundSource).toMatch(/href='\/'/)
  expect(catchAllSource).toMatch(/notFound\(\)/)
})

test('CI runs the complete documented quality gate', async () => {
  const workflowSource = await readProjectFile('.github/workflows/quality.yml')

  expect(workflowSource).toMatch(/permissions:\s+contents: read/)
  for (const command of ['format:check', 'lint', 'typecheck', 'ui:check-icons', 'icons:check', 'test', 'build']) {
    expect(workflowSource).toMatch(new RegExp(`run: pnpm ${command.replace(':', '\\:')}`))
  }
  expect(workflowSource).toMatch(/playwright install --with-deps chromium/)
})

test('integration recipes document the implemented boundaries', async () => {
  const [openApiSource, tolgeeSource] = await Promise.all([
    readProjectFile('docs/recipes/openapi-codegen.md'),
    readProjectFile('docs/recipes/tolgee.md')
  ])

  expect(openApiSource).toMatch(/pnpm generate/i)
  expect(openApiSource).toMatch(/src\/api\/example-service/i)
  expect(openApiSource).toMatch(/--axios/)
  expect(openApiSource).toMatch(/contract/i)
  expect(tolgeeSource).toMatch(/namespace/i)
  expect(tolgeeSource).toMatch(/Do not call `changeLanguage\(\)` during render/)
  expect(tolgeeSource).toMatch(/TOLGEE_API_KEY/)
})
