import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { format, resolveConfig } from 'prettier'

type IconData = {
  body: string
  width?: number
  height?: number
  left?: number
  top?: number
  rotate?: number
  hFlip?: boolean
  vFlip?: boolean
}

type IconSet = {
  prefix: string
  width?: number
  height?: number
  icons: Record<string, IconData>
}

const projectRoot = process.cwd()
const iconConfigPath = path.join(projectRoot, 'src', 'config', 'icons.ts')
const generatedPath = path.join(projectRoot, 'src', 'config', 'icon-data.ts')
const collectionPath = path.join(projectRoot, 'node_modules', '@iconify-json', 'lucide', 'icons.json')
const writeMode = process.argv.includes('--write')

const [configSource, collectionSource] = await Promise.all([
  readFile(iconConfigPath, 'utf8'),
  readFile(collectionPath, 'utf8')
])
const collection = JSON.parse(collectionSource) as IconSet
const configuredIcons = [...configSource.matchAll(/\b[A-Za-z\d_$]+:\s*'([^']+)'/g)].map(match => match[1])

if (!configuredIcons.length) throw new Error('No icon IDs were found in src/config/icons.ts.')

const offlineIcons: Record<string, IconData> = {}
const missingIcons: string[] = []

for (const fullName of configuredIcons) {
  const [prefix, name, ...rest] = fullName.split(':')
  if (prefix !== collection.prefix || !name || rest.length) {
    missingIcons.push(fullName)
    continue
  }

  const icon = collection.icons[name]
  if (!icon) {
    missingIcons.push(fullName)
    continue
  }

  offlineIcons[fullName] = {
    ...icon,
    width: icon.width ?? collection.width ?? 24,
    height: icon.height ?? collection.height ?? 24
  }
}

if (missingIcons.length) {
  throw new Error(`Icons missing from the bundled Lucide collection: ${missingIcons.join(', ')}`)
}

const rawOutput = `// Generated by pnpm icons:generate. Do not edit manually.\n\nimport type { IconifyIcon } from '@iconify/react'\n\nexport const offlineIcons = ${JSON.stringify(offlineIcons, null, 2)} satisfies Record<string, IconifyIcon>\n`
const prettierConfig = (await resolveConfig(generatedPath)) ?? {}
const output = await format(rawOutput, { ...prettierConfig, filepath: generatedPath })

if (writeMode) {
  await writeFile(generatedPath, output, 'utf8')
  console.log(`Bundled ${configuredIcons.length} Lucide icons for offline rendering.`)
  process.exit(0)
}

let current = ''
try {
  current = await readFile(generatedPath, 'utf8')
} catch {
  // The comparison below reports the command that creates a missing generated file.
}

if (current !== output) {
  console.error('Offline icon data is out of date. Run pnpm icons:generate.')
  process.exit(1)
}

console.log(`Offline icon data is current (${configuredIcons.length} icons).`)
