// This file is generated by scripts/tolgee/sync-repository.mts.
// Do not edit it manually.

export const namespaces = ['common'] as const

export type TranslationNamespace = (typeof namespaces)[number]

export const defaultNamespace: TranslationNamespace = 'common'

export const staticData = {
  'th:common': () => import('../../langs/common/th.json').then(module => module.default),
  'en:common': () => import('../../langs/common/en.json').then(module => module.default)
}
