import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, extname, join, relative, resolve } from 'node:path'

import { format, resolveConfig } from 'prettier'

const SUPPORTED_LOCALES = ['th', 'en'] as const
const DEFAULT_NAMESPACE = 'common'
const NAMESPACE_PATTERN = /^[A-Za-z][A-Za-z0-9_-]*$/
const TRANSLATION_CALL_PATTERN = /\bt\(\s*(['"])((?:\\.|[^\\])*?)\1\s*,\s*(['"])((?:\\.|[^\\])*?)\3/g

type FlatTranslations = Record<string, string>
type TranslationCatalogs = Record<string, Record<(typeof SUPPORTED_LOCALES)[number], FlatTranslations>>

export type RepositorySyncResult = {
  namespaces: string[]
  sourceFilesChanged: number
  fallbacksChanged: number
  filesCreated: string[]
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function flattenTranslations(value: unknown, prefix = '', result: FlatTranslations = {}): FlatTranslations {
  if (!isRecord(value)) {
    throw new Error('A translation catalog must contain a JSON object at its root.')
  }

  for (const [key, entry] of Object.entries(value)) {
    const path = prefix ? `${prefix}.${key}` : key

    if (typeof entry === 'string') {
      result[path] = entry
    } else if (isRecord(entry)) {
      flattenTranslations(entry, path, result)
    } else {
      throw new Error(`Translation "${path}" must be a string or nested object.`)
    }
  }

  return result
}

function escapeStringLiteral(value: string, quote: string) {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')
    .replaceAll('\t', '\\t')
    .replaceAll(quote, `\\${quote}`)
}

export function updateTranslationDefaults(source: string, translations: Map<string, string>) {
  let fallbacksChanged = 0
  const missingKeys = new Set<string>()

  const updatedSource = source.replace(
    TRANSLATION_CALL_PATTERN,
    (match, _keyQuote: string, fullKey: string, valueQuote: string, previousValue: string) => {
      if (!fullKey.includes(':')) return match

      const translatedValue = translations.get(fullKey)

      if (translatedValue === undefined) {
        missingKeys.add(fullKey)
        return match
      }

      const escapedValue = escapeStringLiteral(translatedValue, valueQuote)

      if (escapedValue === previousValue) return match

      fallbacksChanged += 1
      return `${match.slice(0, match.length - previousValue.length - 1)}${escapedValue}${valueQuote}`
    }
  )

  return { source: updatedSource, fallbacksChanged, missingKeys: [...missingKeys].sort() }
}

function createGeneratedConfig(namespaces: string[]) {
  const namespaceLines = namespaces.map(namespace => `  '${namespace}'`).join(',\n')
  const staticDataLines = namespaces
    .flatMap(namespace =>
      SUPPORTED_LOCALES.map(
        locale =>
          `  '${locale}:${namespace}': () => import('../../langs/${namespace}/${locale}.json').then(module => module.default)`
      )
    )
    .join(',\n')

  return `// This file is generated by scripts/tolgee/sync-repository.mts.\n// Do not edit it manually.\n\nexport const namespaces = [\n${namespaceLines}\n] as const\n\nexport type TranslationNamespace = (typeof namespaces)[number]\n\nexport const defaultNamespace: TranslationNamespace = '${DEFAULT_NAMESPACE}'\n\nexport const staticData = {\n${staticDataLines}\n}\n`
}

async function collectSourceFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async entry => {
      const path = join(directory, entry.name)
      return entry.isDirectory() ? collectSourceFiles(path) : [path]
    })
  )

  return files.flat().filter(path => ['.ts', '.tsx'].includes(extname(path)))
}

async function readCatalog(path: string) {
  let value: unknown

  try {
    value = JSON.parse(await readFile(path, 'utf8'))
  } catch (error) {
    throw new Error(`Unable to read translation catalog ${relative(resolve(), path)}.`, { cause: error })
  }

  return flattenTranslations(value)
}

async function discoverNamespaces(langsDirectory: string, write: boolean) {
  if (write) await mkdir(langsDirectory, { recursive: true })
  const entries = await readdir(langsDirectory, { withFileTypes: true })
  const namespaces = entries.filter(entry => entry.isDirectory()).map(entry => entry.name)

  if (!namespaces.includes(DEFAULT_NAMESPACE)) {
    namespaces.push(DEFAULT_NAMESPACE)

    if (write) await mkdir(join(langsDirectory, DEFAULT_NAMESPACE), { recursive: true })
  }

  for (const namespace of namespaces) {
    if (!NAMESPACE_PATTERN.test(namespace)) {
      throw new Error(`Invalid Tolgee namespace directory: ${namespace}`)
    }
  }

  return namespaces.sort()
}

export async function syncTranslationRepository({
  write,
  rootDirectory = resolve()
}: {
  write: boolean
  rootDirectory?: string
}): Promise<RepositorySyncResult> {
  const root = resolve(rootDirectory)
  const langsDirectory = join(root, 'langs')
  const generatedConfigPath = join(root, 'src/tolgee/config.ts')
  const sourceDirectory = join(root, 'src')
  const namespaces = await discoverNamespaces(langsDirectory, write)
  const filesCreated: string[] = []
  const catalogs: TranslationCatalogs = {}

  for (const namespace of namespaces) {
    const namespaceDirectory = join(langsDirectory, namespace)
    if (write) await mkdir(namespaceDirectory, { recursive: true })
    catalogs[namespace] = { th: {}, en: {} }

    for (const locale of SUPPORTED_LOCALES) {
      const catalogPath = join(namespaceDirectory, `${locale}.json`)

      try {
        catalogs[namespace][locale] = await readCatalog(catalogPath)
      } catch (error) {
        const cause = error instanceof Error && error.cause

        if (cause && typeof cause === 'object' && 'code' in cause && cause.code === 'ENOENT') {
          filesCreated.push(relative(root, catalogPath).replaceAll('\\', '/'))

          if (write) {
            await writeFile(catalogPath, '{}\n', 'utf8')
          }

          continue
        }

        throw error
      }
    }
  }

  const fallbackTranslations = new Map<string, string>()

  for (const namespace of namespaces) {
    const allKeys = new Set([...Object.keys(catalogs[namespace].th), ...Object.keys(catalogs[namespace].en)])

    for (const key of allKeys) {
      const thai = catalogs[namespace].th[key]
      const english = catalogs[namespace].en[key]
      const fallback = thai?.trim() ? thai : english

      if (fallback !== undefined) fallbackTranslations.set(`${namespace}:${key}`, fallback)
    }
  }

  const prettierConfig = (await resolveConfig(generatedConfigPath)) ?? {}
  const expectedConfig = await format(createGeneratedConfig(namespaces), {
    ...prettierConfig,
    filepath: generatedConfigPath
  })
  const currentConfig = await readFile(generatedConfigPath, 'utf8').catch(() => '')
  const configChanged = currentConfig !== expectedConfig

  if (write && configChanged) {
    await mkdir(dirname(generatedConfigPath), { recursive: true })
    await writeFile(generatedConfigPath, expectedConfig, 'utf8')
  }

  let sourceFilesChanged = 0
  let fallbacksChanged = 0
  const missingKeys = new Set<string>()
  const sourceFiles = await collectSourceFiles(sourceDirectory)

  for (const sourcePath of sourceFiles) {
    const source = await readFile(sourcePath, 'utf8')
    const updated = updateTranslationDefaults(source, fallbackTranslations)

    updated.missingKeys.forEach(key => missingKeys.add(key))

    if (updated.source !== source) {
      sourceFilesChanged += 1
      fallbacksChanged += updated.fallbacksChanged

      if (write) await writeFile(sourcePath, updated.source, 'utf8')
    }
  }

  if (missingKeys.size > 0) {
    throw new Error(`Source translation keys are missing from langs/: ${[...missingKeys].join(', ')}`)
  }

  const drift = [
    ...(filesCreated.length ? [`missing locale files: ${filesCreated.join(', ')}`] : []),
    ...(configChanged ? ['src/tolgee/config.ts is stale'] : []),
    ...(fallbacksChanged ? [`${fallbacksChanged} source fallback(s) are stale`] : [])
  ]

  if (!write && drift.length > 0) {
    throw new Error(`Tolgee repository state is stale. Run pnpm i18n:generate.\n- ${drift.join('\n- ')}`)
  }

  return { namespaces, sourceFilesChanged, fallbacksChanged, filesCreated }
}
